name: alexchenesq
favicon: null
layout_spectrum: 0.07701613404788077
typography_spectrum: 0.14412280567921698
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e4e4e4'
    - '#4d4d4d'
    - '#8c8c8c'
    - '#0f0f0f'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.3733583160210401
purpose: []
