name: alexchenesq
favicon: null
layout_spectrum: 0.07701613404788077
typography_spectrum: 0.14412280567921698
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#556c77'
    - '#020202'
    - '#ffffff'
    - '#cbd0d0'
    - '#989ea4'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
